m<-rbind(c(1,2),c(3,4),c(5,6))
layout(m)
x<-rep(1,12)
par(mar = c(1,1,1,1))
barplot(x, col=rainbow(12),main = "col=rainbow(12)",axes = F)
barplot(x, col=heat.colors(12),main = "col=heat.colors(12)",axes = F)
barplot(x, col=terrain.colors(12),main = "col=terrain.colors(12)",axes = F)
barplot(x, col=topo.colors(12),main = "col=topo.colors(12)",axes = F)
barplot(x, col=cm.colors(12),main = "col=cm.colors(12)",axes = F)
barplot(x, col=grey((0:11)/11),main = "col=grey((0:11)/11)",axes = F)
